# **Mis apuntes sobre Python**
En este cuaderno recojo algunos apuntes sobre Python

**Variables**

La definición de las variables no lleva ninguna palabra reservada, simplemente se define la variable y se le da un valor. Si simplemente queremos declararla, deberemos darle un valor de referencia para que infiera el tipo.

In [ ]:
variable = 3
variable

3

**Listas**

Las listas son los arrays en otros lenguajes, y funcionan de igual forma entre [ ].

Para añadir un elemento en una lista se usa *append*.

In [ ]:
lista = [1,2,3,4,5,6,7]
lista.append(8)
lista

[1, 2, 3, 4, 5, 6, 7, 8]

Para obtener la longitud de la lista (número de elementos) se emplea *len*.

In [ ]:
len(lista)

8

Si queremos obtener un valor de la lista, se hace de la siguiente manera. También pueden obtenerse contando por el final si se ponen números negativos

In [ ]:
lista[1]

2

In [ ]:
lista[-1]

8

Para tomar los datos de cierta columna de una matriz sería de la siguiente manera (es útil numpy para trabajar con arrays y no con listas):

In [ ]:
import numpy as np

matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]
np.array(matriz)[:,1]

array([2, 5, 8])

**Diccionarios**

Son conjuntos de pares clave valor. No puede haber claves repetidas pero sí valores. Si se asigna un nuevo valor a una clave que ya existe en el diccionario, ésta se sobreescribe. Van entre {}.

In [ ]:
diccionario = {'clave 01': 2,
               'clave 02': 'prueba',
               'clave 03': True,
               'clave 04': [1,2,3,4]}
diccionario

{'clave 01': 2,
 'clave 02': 'prueba',
 'clave 03': True,
 'clave 04': [1, 2, 3, 4]}

Para conocer las claves se usa *keys()*.

In [ ]:
diccionario.keys()

dict_keys(['clave 01', 'clave 02', 'clave 03', 'clave 04'])

Para conocer los valores se usa *values()*.

In [ ]:
diccionario.values()

dict_values([2, 'prueba', True, [1, 2, 3, 4]])

Para conocer los elementos de un diccionario, se emplea *items()*.

In [ ]:
diccionario.items()

dict_items([('clave 01', 2), ('clave 02', 'prueba'), ('clave 03', True), ('clave 04', [1, 2, 3, 4])])

**Bucles**

In [ ]:
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
for elemento in lista:
  print(elemento)

1
2
3
4
5
6
7
8


In [ ]:
nueva_lista = []
for elemento in lista:
  nueva_lista.append(elemento+2)
nueva_lista

[3, 4, 5, 6, 7, 8, 9, 10]

Es muy útil poder reducir el *for* anterior a una sola línea si se quiere operar sobre cada uno de los elementos

In [ ]:
nueva_lista_2 = [elemento + 2 for elemento in lista]
nueva_lista_2

[3, 4, 5, 6, 7, 8, 9, 10]

**Funciones**

Las funciones se definen con *def*:

In [ ]:
def nueva_funcion():
  print('Este es el resultado de la función')

nueva_funcion()

Este es el resultado de la función


Si queremos que una función no devuelva nada se le puede poner *pass*:

In [ ]:
def funcion_que_no_hace_nada():
  pass

funcion_que_no_hace_nada()

También puede definirse la función para que devuelva algo

In [ ]:
def funcion_que_devuelve_algo():
  return 'Hola'
print(funcion_que_devuelve_algo())

Hola


Se le pueden pasar parámetros a la función indicando los argumentos entre los paréntesis

In [ ]:
def suma(a,b):
  print(a+b)
suma(1,2)

3


**Clases**

Como en otros lenguajes de programación, las clases contienen propiedades y métodos. En este caso particular tiene una función de inicio (que se ejecuta al instanciar la clase) que se llama *__init__(self)* (self es para referirse a la clase en cuestión).
Por convención, suelen nombrarse con la primera letra en mayúscula.

In [ ]:
class Persona():
  
  def __init__(self):
    self.nombre = 'Javier'
    self.apellido= 'Lledó'

  def presentarse(self):
    print('Hola, me llamo', self.nombre, self.apellido)

Hola, me llamo Javier Lledó


Para instanciarla simplemente se hace de la siguiente manera:

In [ ]:
persona = Persona()
persona.presentarse()

Hola, me llamo Javier Lledó


También puede usarse __init__ como constructor, y a la hora de instanciarlo pasarle esos parámetros

In [ ]:
class Persona02():

  def __init__(self, nombre, apellido):
    self.nombre = nombre
    self.apellido= apellido

  def presentarse(self):
    print('Hola, me llamo', self.nombre, self.apellido)

persona02 = Persona02(nombre='Javier', apellido = 'Lledó')
persona02.presentarse()

Hola, me llamo Javier Lledó


**Librerías**

Pueden importarse librerías para poder usar sus funciones con *import*, y puede indicarse de qué manera hacer referencia a ellas.

In [ ]:
import random
random.random()

0.46818641822142293

Algunas librerías interesantes son las siguientes (junto con los códigos que suelen usarse para referenciarse):

*   random
*   numpy (np). Computación numérica
*   scipy (sc)
*   sklearn (sk). De ésta también se pueden descargar datasets. 
*   scikit-learn
*   Tensorflow
*   keras
*   plotly
*   matplotlib.pyplot (plt)
*   matpltolib
*   matplotlib
*   seaborn
*   statmodels
*   pandas


**Librería Numpy**

.array para crear un array. En Numpy trabaja con arrays que sería el equivalente a las listas de Python

.transpose para transponer una matriz, aunque con .T también es válido

@ se usa para la multiplicación matricial, aunque esto es genérico de Python

.ones para un array de unos

.linealg.inv es la inversa de una matriz

In [ ]:
import numpy as np

matriz = [[1,2,3],[4,5,6],[7,8,9]]

np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz_traspuesta = np.transpose(matriz)
matriz_traspuesta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matriz @ matriz_traspuesta

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
##Se ha cambiado de matriz en el ejemplo porque la anterior era singular
matriz_nueva = [[1,5,3],[5,9,8],[8,9,7]]
np.linalg.inv(matriz_nueva)

array([[-0.16363636, -0.14545455,  0.23636364],
       [ 0.52727273, -0.30909091,  0.12727273],
       [-0.49090909,  0.56363636, -0.29090909]])

**Herramientas de análisis por explorar**
* Knime
* Weka
* Dataiku
* BigML