#El método de k-means

Recordar que 

In [119]:
import numpy as np

In [120]:
data = np.random.random(90).reshape(30,3)
data

array([[0.72124194, 0.87036171, 0.68930283],
       [0.96971683, 0.72394333, 0.00264517],
       [0.35818748, 0.67761479, 0.0092635 ],
       [0.11794166, 0.31041021, 0.26176852],
       [0.98560161, 0.89138562, 0.12150622],
       [0.33365406, 0.08401354, 0.91005316],
       [0.59191265, 0.15292345, 0.14226969],
       [0.98160403, 0.49302138, 0.67835559],
       [0.5879048 , 0.40385765, 0.93002169],
       [0.92731492, 0.22567751, 0.93159929],
       [0.58542856, 0.55361783, 0.80672247],
       [0.30386563, 0.36936518, 0.76125661],
       [0.00595745, 0.90812844, 0.00387073],
       [0.11059734, 0.7273041 , 0.01349112],
       [0.15096584, 0.41737191, 0.04736709],
       [0.09222825, 0.88707924, 0.22950613],
       [0.56912449, 0.77801051, 0.55704337],
       [0.79932512, 0.45603289, 0.80947784],
       [0.94251845, 0.53218364, 0.01579047],
       [0.84399692, 0.17908678, 0.76259653],
       [0.40054168, 0.18698038, 0.86607636],
       [0.98529378, 0.04506049, 0.72967443],
       [0.

In [121]:
#Elegimos dos puntos al azar para determinar que esos puntos serán los centroides
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_center = np.vstack([data[c1], data[c2]])
clust_center

array([[0.40054168, 0.18698038, 0.86607636],
       [0.00595745, 0.90812844, 0.00387073]])

In [122]:
from scipy.cluster.vq import vq

In [123]:
vq(data, clust_center)
#El primer resultado es el clúster al que pertenece cada punto
#El segundo resultado nos da la distancia de cada una de las observaciones a su cluster

(array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
 array([0.77531129, 0.98120222, 0.42098886, 0.66054434, 0.98682375,
        0.1304227 , 0.74945235, 0.68303268, 0.29364894, 0.53224128,
        0.4148844 , 0.23151168, 0.        , 0.20913991, 0.513577  ,
        0.24248104, 0.68792308, 0.4843768 , 1.00926858, 0.45543709,
        0.        , 0.61699413, 0.81569158, 0.37011886, 0.69577691,
        0.46810075, 0.67923293, 0.6478975 , 0.81089593, 0.56091767]))

In [124]:
from scipy.cluster.vq import kmeans

In [125]:
kmeans(data, clust_center)
# Ojo que el resultado no son los centros de los clusters sino los baricentros del conjunto de datos que pertenecen a un 
# El segundo número es el error cuadrático medio normalizado

(array([[0.65590753, 0.37436176, 0.77580295],
        [0.48489721, 0.59256657, 0.11367081]]), 0.41144786050983223)

In [126]:
kmeans(data, 2) #Organizados en dos clusters

(array([[0.66133147, 0.34913371, 0.78947543],
        [0.49091345, 0.60581257, 0.14534028]]), 0.4106502044583403)